### ISSUE TITLE
钉钉扫码后修改密码报错  错误[cannot unpack non-iterable NoneType object]，请与管理员联系.

### ISSUE THREAD

**Issue by zhaowei2021** [capricornxl/ad-password-self-service#21]
错误[cannot unpack non-iterable NoneType object]，请与管理员联系.
log.log日志报错信息：
2022-06-24 10:03:05,025 INFO ./resetpwd/views.py views.callback_check 127: [成功]  请求方法：GET，请求路径：/callbackCheck，CODE：ac63e37ee0383316b34e876d82446a72
2022-06-24 10:03:05,275 DEBUG /usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/base.py base._resolve_lookup 869: Exception while resolving variable 'unsecpwd' in template 'resetPassword.v1.html'.
Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'unsecpwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'unsecpwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'unsecpwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [unsecpwd] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: 'ztZtQV5e4cpnSFl8CUqSxnL4pp37QHuRMNzhqKx8d3sBy8DsCHWtatBGbIYdVWTn'>, 'request': <WSGIRequest: GET '/resetPassword'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7f068cab6f70>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f068ca54670>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f068ca54a90>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'username': 'zhaowei'}]
2022-06-24 10:03:30,888 ERROR ./resetpwd/views.py views.reset_pwd_by_callback 221: [异常] ：cannot unpack non-iterable NoneType object

**Comment by capricornxl** [comment]
看下resetpwd/views.py中的def index下的代码：
里面有没有一个unsecpwd = settings.UN_SEC_PASSWORD
UN_SEC_PASSWORD是在settings中配置的不安全的密码。
