### ISSUE TITLE
自动脚本部署成功后网址502

### ISSUE THREAD

**Issue by yuzhifei** [capricornxl/ad-password-self-service#32]
系统：centos 8
内核版本：4.18.0-240.el8.x86_64
安装版本：ad-password-self-service-master 2月10日更新版本
现象：使用一键部署脚本安装成功后，打开域名502。

一键安装的时候我是把ad-password-self-service-master这个目录放在/tmp下执行的 部署脚本./auto-install.sh。是否需要把哪个目录复制到nginx所在的什么目录下才不会报502错误？

**Comment by capricornxl** [comment]
脚本中有个参数是根据当前执行的目录做为主目录的。
会自动把当前的路径替换到对应的启动脚本和配置文件中。
502的报错和Nginx本身无关，502是服务端响应失败，问题应该是在Uwsgi上，你检查下Uwsgi的启动状态，再看下它的日志。如果是路径或配置有问题，日志中会有详细的显示。


------ 原始信息 ------
来自 "yuzhifei" ***@***.******@***.***>>
收件人 "capricornxl/ad-password-self-service" ***@***.******@***.***>>
抄送 "Subscribed" ***@***.******@***.***>>
日期 2023/3/18 14:11:04
主题 [capricornxl/ad-password-self-service] 自动脚本部署成功后网址502 (Issue #32)


系统：centos 8
内核版本：4.18.0-240.el8.x86_64
安装版本：ad-password-self-service-master 2月10日更新版本
现象：使用一键部署脚本安装成功后，打开域名502。

一键安装的时候我是把ad-password-self-service-master这个目录放在/tmp下执行的 部署脚本./auto-install.sh。是否需要把哪个目录复制到nginx所在的什么目录下才不会报502错误？

**Comment by yuzhifei** [comment]
Uwsgi的启动状态。
[root@ssp ad-password-self-service-master]# systemctl status uwsgiserver
● uwsgiserver.service - SYSV: uwsgi server is Web Server
   Loaded: loaded (/etc/rc.d/init.d/uwsgiserver; generated)
   Active: active (exited) since Wed 2023-03-15 22:29:48 CST; 3 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1130 ExecStart=/etc/rc.d/init.d/uwsgiserver start (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 23495)
   Memory: 0B
   CGroup: /system.slice/uwsgiserver.service

/log/uwsgi.log的日志信息。
*** Operational MODE: preforking+threaded ***
Redis无法连接，请排查Redis配置...
Traceback (most recent call last):
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 58, in __getitem__
    return getattr(self._connections, alias)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/asgiref/local.py", line 105, in __getattr__
    raise AttributeError(f"{self!r} object has no attribute {key!r}")
AttributeError: <asgiref.local.Local object at 0x7f65347a1c10> object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ad-password-self-service-master/./pwdselfservice/__init__.py", line 11, in <module>
    redis_conn = get_redis_connection()
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django_redis/__init__.py", line 12, in get_redis_connection
    cache = caches[alias]
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 60, in __getitem__
    if alias not in self.settings:
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/share/python-3.8.16/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ad-password-self-service-master/./pwdselfservice/settings.py", line 11, in <module>
    from conf.local_settings import REDIS_LOCATION, REDIS_PASSWORD
ImportError: cannot import name 'REDIS_LOCATION' from 'conf.local_settings' (/tmp/ad-password-self-service-master/./conf/local_settings.py)

**Comment by capricornxl** [comment]
看起来是Redis的问题，
先看下Redis服务的运行状态，如果运行是正常的。
可以看一下redis的配置文件中requirepass这个参数后面有没有生成密码，再看下conf/local_settings.py下的REDIS_PASSWORD后面是否也有密码。

如果都没有，可以手动给Redis配置一个密码并重启redis服务，同时把密码配置到conf/local_settings.py，然后重启uwsgiserver



------ 原始信息 ------
来自 "yuzhifei" ***@***.******@***.***>>
收件人 "capricornxl/ad-password-self-service" ***@***.******@***.***>>
抄送 "Yadeno" ***@***.******@***.***>>; "Comment" ***@***.******@***.***>>
日期 2023/3/20 09:13:16
主题 Re: [capricornxl/ad-password-self-service] 自动脚本部署成功后网址502 (Issue #32)


Uwsgi的启动状态。
***@***.*** ad-password-self-service-master]# systemctl status uwsgiserver
● uwsgiserver.service - SYSV: uwsgi server is Web Server
Loaded: loaded (/etc/rc.d/init.d/uwsgiserver; generated)
Active: active (exited) since Wed 2023-03-15 22:29:48 CST; 3 days ago
Docs: man:systemd-sysv-generator(8)
Process: 1130 ExecStart=/etc/rc.d/init.d/uwsgiserver start (code=exited, status=0/SUCCESS)
Tasks: 0 (limit: 23495)
Memory: 0B
CGroup: /system.slice/uwsgiserver.service

/log/uwsgi.log的日志信息。
*** Operational MODE: preforking+threaded ***
Redis无法连接，请排查Redis配置...
Traceback (most recent call last):
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 58, in getitem
return getattr(self._connections, alias)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/asgiref/local.py", line 105, in getattr
raise AttributeError(f"{self!r} object has no attribute {key!r}")
AttributeError: <asgiref.local.Local object at 0x7f65347a1c10> object has no attribute 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/ad-password-self-service-master/./pwdselfservice/init.py", line 11, in
redis_conn = get_redis_connection()
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django_redis/init.py", line 12, in get_redis_connection
cache = caches[alias]
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 60, in getitem
if alias not in self.settings:
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in get
res = instance.dict[self.name] = self.func(instance)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
self._settings = self.configure_settings(self._settings)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
settings = getattr(django_settings, self.settings_name)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/init.py", line 82, in getattr
self._setup(name)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/init.py", line 69, in _setup
self._wrapped = Settings(settings_module)
File "/tmp/ad-password-self-service-master/pwd_venv/lib/python3.8/site-packages/django/conf/init.py", line 170, in init
mod = importlib.import_module(self.SETTINGS_MODULE)
File "/usr/share/python-3.8.16/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 843, in exec_module
File "", line 219, in _call_with_frames_removed
File "/tmp/ad-password-self-service-master/./pwdselfservice/settings.py", line 11, in
from conf.local_settings import REDIS_LOCATION, REDIS_PASSWORD
ImportError: cannot import name 'REDIS_LOCATION' from 'conf.local_settings' (/tmp/ad-password-self-service-master/./conf/local_settings.py)

**Comment by yuzhifei** [comment]
# ####### Redis ##########
REDIS_LOCATION = r'127.0.0.1:6379'
REDIS_PASSWORD = r'PWD_SELF_REDIS_PASSWORD'

我这边手动添加到文件末尾，重启了服务器，现在/log/uwsgi.log的日志信息如下：

*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 20 16:38:20 2023] ***
compiled with version: 8.5.0 20210514 (Red Hat 8.5.0-18) on 15 March 2023 14:07:37
os: Linux-4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020
nodename: ssp
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /tmp/ad-password-self-service-master/pwd_venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /tmp/ad-password-self-service-master
your processes number limit is 14684
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Cannot assign requested address [core/socket.c line 769]

文件里确实没有这2行记录，那是需要重新再部署一遍吗？

**Comment by capricornxl** [comment]
先不用，晚点我开台Centos的跑一下脚本，看看具体啥原因。
Centos我目前测试得比较少，主要业务用Ubuntu比较多~🤣


------ 原始信息 ------
来自 "yuzhifei" ***@***.******@***.***>>
收件人 "capricornxl/ad-password-self-service" ***@***.******@***.***>>
抄送 "Yadeno" ***@***.******@***.***>>; "Comment" ***@***.******@***.***>>
日期 2023/3/20 17:14:57
主题 Re: [capricornxl/ad-password-self-service] 自动脚本部署成功后网址502 (Issue #32)


####### Redis

REDIS_LOCATION = r'127.0.0.1:6379'
REDIS_PASSWORD = r'PWD_SELF_REDIS_PASSWORD'

我这边手动添加到文件末尾，重启了服务器，现在/log/uwsgi.log的日志信息如下：

*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 20 16:38:20 2023] ***
compiled with version: 8.5.0 20210514 (Red Hat 8.5.0-18) on 15 March 2023 14:07:37
os: Linux-4.18.0-240.el8.x86_64 #1<https://github.com/capricornxl/ad-password-self-service/issues/1> SMP Fri Sep 25 19:48:47 UTC 2020
nodename: ssp
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /tmp/ad-password-self-service-master/pwd_venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /tmp/ad-password-self-service-master
your processes number limit is 14684
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Cannot assign requested address [core/socket.c line 769]

文件里确实没有这2行记录，那是需要重新再部署一遍吗？

**Comment by capricornxl** [comment]
你好，这我用Centos8跑自动部署脚本，确实存在一些问题，问题似乎是连接源失败，然后导致一些依赖包没装上引起的。
国内的一些Yum源经常抽风，不太稳定。

------ 原始信息 ------
来自 "向乐" ***@***.******@***.***>>
收件人 "capricornxl/ad-password-self-service" ***@***.******@***.***>>; "capricornxl/ad-password-self-service" ***@***.******@***.***>>
抄送 "Comment" ***@***.******@***.***>>
日期 2023/3/20 17:16:21
主题 Re[2]: [capricornxl/ad-password-self-service] 自动脚本部署成功后网址502 (Issue #32)

先不用，晚点我开台Centos的跑一下脚本，看看具体啥原因。
Centos我目前测试得比较少，主要业务用Ubuntu比较多~🤣


------ 原始信息 ------
来自 "yuzhifei" ***@***.******@***.***>>
收件人 "capricornxl/ad-password-self-service" ***@***.******@***.***>>
抄送 "Yadeno" ***@***.******@***.***>>; "Comment" ***@***.******@***.***>>
日期 2023/3/20 17:14:57
主题 Re: [capricornxl/ad-password-self-service] 自动脚本部署成功后网址502 (Issue #32)


####### Redis

REDIS_LOCATION = r'127.0.0.1:6379'
REDIS_PASSWORD = r'PWD_SELF_REDIS_PASSWORD'

我这边手动添加到文件末尾，重启了服务器，现在/log/uwsgi.log的日志信息如下：

*** Starting uWSGI 2.0.21 (64bit) on [Mon Mar 20 16:38:20 2023] ***
compiled with version: 8.5.0 20210514 (Red Hat 8.5.0-18) on 15 March 2023 14:07:37
os: Linux-4.18.0-240.el8.x86_64 #1<https://github.com/capricornxl/ad-password-self-service/issues/1> SMP Fri Sep 25 19:48:47 UTC 2020
nodename: ssp
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /tmp/ad-password-self-service-master/pwd_venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /tmp/ad-password-self-service-master
your processes number limit is 14684
your memory page size is 4096 bytes
detected max file descriptor number: 1024
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Cannot assign requested address [core/socket.c line 769]

文件里确实没有这2行记录，那是需要重新再部署一遍吗？

**Comment by yuzhifei** [comment]
好的。我已经用ubuntu重新部署了一台服务，但是目前还是有一些小问题，方便加个QQ:252987765帮忙解答一下吗？

**Comment by capricornxl** [comment]
> 252987765

大佬，己加。
