### ISSUE TITLE
自动部署的，点击重置密码 出来  的是Server Error (500)

### ISSUE THREAD

**Issue by z15858167** [capricornxl/ad-password-self-service#36]
AD 域服务器安装证书服务了，里面也有颁发的证书。不知道这样是不是就可以使用636了。conf里的文件也修改了。授权的用户也添加了修改密码的权限 。但我感觉server error 500应该是没跟AD域连接成功。

**Comment by z15858167** [comment]
还有，/etc/init.d/uwsigserver start 需要执行两遍。才可以启动服务。

**Comment by z15858167** [comment]
DC=test,DC=local

**Comment by capricornxl** [comment]
看下日志的报错内容是啥，500和AD没关系，服务本身启动有问题。

**Comment by z15858167** [comment]
没想到大佬立刻回复了，我看看

**Comment by z15858167** [comment]
2023-08-26 13:06:43,386 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 13:06:43,394 ERROR /usr/share/python-3.8.9/lib/python3.8/site-packages/django/utils/log.py log.log_response 224: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resetpwd/views.py", line 74, in index
    _msg = check_form.as_p().errors
AttributeError: 'SafeString' object has no attribute 'errors'
2023-08-26 14:23:54,878 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 14:23:54,881 ERROR /usr/share/python-3.8.9/lib/python3.8/site-packages/django/utils/log.py log.log_response 224: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resetpwd/views.py", line 74, in index
    _msg = check_form.as_p().errors
AttributeError: 'SafeString' object has no attribute 'errors'

**Comment by z15858167** [comment]
是点击 提交后返回500

**Comment by capricornxl** [comment]
看着像是BUG，你把
./resetpwd/views.py的第74行
_msg = check_form.as_p().errors
这里的check_form.as_p().errors改成check_form.as_p()，然后再重启下uwsgiserver。

**Comment by z15858167** [comment]
修改完了之后，后报错日志
[root@localhost log]# tail -f log.log
2023-08-26 15:19:58,147 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 15:19:58,155 ERROR /usr/share/python-3.8.9/lib/python3.8/site-packages/django/utils/log.py log.log_response 224: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resetpwd/views.py", line 75, in index
    logger.error('[异常]  请求方法：%s，请求路径：%s，错误信息：%s' % (request.method, request.path, _msg))
NameError: name '_msg' is not defined
2023-08-26 15:21:02,869 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 15:21:02,872 ERROR /usr/share/python-3.8.9/lib/python3.8/site-packages/django/utils/log.py log.log_response 224: Internal Server Error: /
Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resetpwd/views.py", line 75, in index
    logger.error('[异常]  请求方法：%s，请求路径：%s，错误信息：%s' % (request.method, request.path, _msg))
NameError: name '_msg' is not defined

**Comment by capricornxl** [comment]
看下你改的地方，你是不是把这一行都改掉了？
是把_msg = check_form.as_p().errors改成_msg = check_form.as_p()

**Comment by z15858167** [comment]
73         else:
 74             _msg = check_form.as_p()
 75             logger.error('[异常]  请求方法：%s，请求路径：%s，错误信息：%s' % (request.method, request.path, _msg))后

**Comment by z15858167** [comment]
2023-08-26 17:02:33,914 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 17:02:33,919 ERROR ./resetpwd/views.py views.index 75: [异常]  请求方法：POST，请求路径：/，错误信息：<ul class="errorlist nonfield"><li>新密码和确认密码输入不一致</li></ul>
<ul class="errorlist"><li>密码长度不能小于8个字符</li><li>密码必须包含数字，字母、特殊字符</li></ul>
<p><label for="id_new_password">New password:</label> <input type="text" name="new_password" value="test" maxlength="30" minlength="8" required id="id_new_password"></p>
<p><label for="id_old_password">Old password:</label> <input type="text" name="old_password" value="test" required id="id_old_password"></p>
<p><label for="id_ensure_password">Ensure password:</label> <input type="text" name="ensure_password" value="test" required id="id_ensure_password"></p>
<p><label for="id_username">Username:</label> <input type="text" name="username" value="test" required id="id_username"></p>

**Comment by z15858167** [comment]
2023-08-26 17:02:33,914 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 17:02:33,919 ERROR ./resetpwd/views.py views.index 75: [异常]  请求方法：POST，请求路径：/，错误信息：<ul class="errorlist nonfield"><li>新密码和确认密码输入不一致</li></ul>
<ul class="errorlist"><li>密码长度不能小于8个字符</li><li>密码必须包含数字，字母、特殊字符</li></ul>
<p><label for="id_new_password">New password:</label> <input type="text" name="new_password" value="test" maxlength="30" minlength="8" required id="id_new_password"></p>
<p><label for="id_old_password">Old password:</label> <input type="text" name="old_password" value="test" required id="id_old_password"></p>
<p><label for="id_ensure_password">Ensure password:</label> <input type="text" name="ensure_password" value="test" required id="id_ensure_password"></p>
<p><label for="id_username">Username:</label> <input type="text" name="username" value="test" required id="id_username"></p>

**Comment by z15858167** [comment]
2023-08-26 17:04:05,460 ERROR ./resetpwd/views.py views.index 60: [异常]  请求方法：POST，请求路径/
2023-08-26 17:04:05,463 ERROR ./resetpwd/views.py views.index 75: [异常]  请求方法：POST，请求路径：/，错误信息：<ul class="errorlist nonfield"><li>新密码和确认密码输入不一致</li></ul>
<ul class="errorlist"><li>密码必须包含数字，字母、特殊字符</li></ul>
<p><label for="id_new_password">New password:</label> <input type="text" name="new_password" value="Wema2012" maxlength="30" minlength="8" required id="id_new_password"></p>
<p><label for="id_old_password">Old password:</label> <input type="text" name="old_password" value="Wema2011" required id="id_old_password"></p>
<p><label for="id_ensure_password">Ensure password:</label> <input type="text" name="ensure_password" value="Wema2012" required id="id_ensure_password"></p>
<p><label for="id_username">Username:</label> <input type="text" name="username" value="test" required id="id_username"></p

**Comment by z15858167** [comment]
修改后

**Comment by capricornxl** [comment]
你现在改完之后的代码是什么样的？
check_form看着在你的代码里是失效了。

**Comment by daniel3155** [comment]
> 还有，/etc/init.d/uwsigserver start 需要执行两遍。才可以启动服务。

我也遇到了这个问题，经常要重启几次才行。

**Comment by capricornxl** [comment]
> > 还有，/etc/init.d/uwsigserver start 需要执行两遍。才可以启动服务。
> 
> 我也遇到了这个问题，经常要重启几次才行。

这种情况可以看下项目目录中log文件夹中的日志，里面会有启动失败的记录，可以对应看看是哪里的问题。
一般启动不了，多半是redis有问题
