### ISSUE TITLE
BN的问题

### ISSUE THREAD

**Issue by aweveeed** [capricornxl/ad-password-self-service#9]
环境说明：
主域系统：windwos2008R2
AD域中以部门建立OU,公司的OU下面有各部门的OU
如果BN 写成 ：OU=gs,DC=abc,DC=com
连接AD域后,会报如下错误 
LDAPInvalidCredentialsResult: 8009030C: LdapErr: DSID-0C0905DF, comment: AcceptSecurityContext error, data 52e, v1db1

错误信息如下：
2021-06-30 15:32:40,298 ERROR ./resetpwd/views.py views.index 68: [异常]  请求方法：POST，请求路径：/
2021-06-30 15:32:40,324 ERROR /usr/share/python-3.8.9/lib/python3.8/site-packages/django/utils/log.py log.log_response 224: Internal Server Error: /
Traceback (most recent call last):
  File "./utils/ad_ops.py", line 56, in __init__
    self.conn = Connection(server, auto_bind=self.auto_bind, user=r'{}\{}'.format(self.domain, self.user), password=self.password,
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/core/connection.py", line 389, in _do_auto_bind
    self.bind(read_server_info=True)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/core/connection.py", line 628, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/core/connection.py", line 1398, in do_ntlm_bind
    response = self.post_send_single_response(self.send('bindRequest', request, controls))
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/strategy/sync.py", line 160, in post_send_single_response
    responses, result = self.get_response(message_id)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/ldap3/strategy/base.py", line 403, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPInvalidCredentialsResult: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 8009030C: LdapErr: DSID-0C0905DF, comment: AcceptSecurityContext error, data 52e, v1db1^@ - bindResponse - None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/share/python-3.8.9/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./resetpwd/views.py", line 90, in index
    auth_status, auth_result = AdOps().ad_auth_user(username=username, password=old_password)
  File "./utils/ad_ops.py", line 59, in __init__
    raise LDAPOperationResult("LDAPInvalidCredentialsResult: " + str(lic_e.message))
ldap3.core.exceptions.LDAPOperationResult: LDAPOperationResult - LDAPInvalidCredentialsResult: 8009030C: LdapErr: DSID-0C0905DF, comment: AcceptSecurityContext error, data 52e, v1db1^@ - None - None - None - None - None

**Comment by aweveeed** [comment]
查了两天问题，看了源代码，调试了才发现，用户密码中不能有^&的字符

**Comment by capricornxl** [comment]
> 查了两天问题，看了源代码，调试了才发现，用户密码中不能有^&的字符

🤣🤣🤣，这ldap3模块的问题吗？

**Comment by capricornxl** [comment]
> 查了两天问题，看了源代码，调试了才发现，用户密码中不能有^&的字符

我测试了下，貌似没有碰到你这样的问题呀？
![image](https://user-images.githubusercontent.com/40738379/124532103-6e059700-de42-11eb-8206-8d3c475073a5.png)

看下你的local_settings.py中的配置。

**Comment by capricornxl** [comment]
目前没有得到任何回复，先关闭了。
